platanus/activeadmin_addons

- lib/activeadmin_addons/addons/paperclip_attachment.rb
- lib/activeadmin_addons/addons/paperclip_image.rb
@ldlsegovia can you check if this is ok? This adds support for nil attachments
> fix(Paperclip): Allow nil values in attachments

- lib/activeadmin_addons/addons/bool_values.rb
- lib/activeadmin_addons/addons/enum_tag.rb
- lib/activeadmin_addons/addons/list.rb
- lib/activeadmin_addons/addons/number.rb
- lib/activeadmin_addons/addons/paperclip_attachment.rb
- lib/activeadmin_addons/addons/paperclip_image.rb
- lib/activeadmin_addons/engine.rb
- lib/activeadmin_addons/support/custom_builder.rb
This PR adds support for blocks and labels(same syntax as usual `column` and `row` of ActiveAdmin)
It uses a `CustomBuilder` class to share logic of extracting data and options
cc @ldlsegovia
> Support for blocks

- lib/activeadmin_addons/support/custom_builder.rb
Helpers were only working with args if used with a block
[Closes #20]
> Fix passing options to addons

- app/assets/stylesheets/activeadmin_addons/all.css.scss
- app/inputs/range_select_input.rb
Para usarlo sólo bastaría con poner esto:
```
filter :barks_count, as: :range_select
```
y se verá así:
> Range Select Input

- lib/activeadmin_addons/addons/enum_tag.rb
When using `activeadmin_addons` in a Rails application that doesn't use `Enumerize`, the application crashes. `Enum` is supported after Rails `4.1`.
> Catching exception caused when application doesn't use Enumerize

- app/assets/javascripts/activeadmin_addons/select2.js
By default in Active Admin, the `select` dropdowns include a blank `option` at the top of the list so the attribute value can be changed to `nil`. However, select2 ignores the blank option unless the `allowClear` option is `true`. Without this PR, there isn't a way to change an attribute that uses a select2 dropdown back to `nil` once it has been changed to any other value.
This PR checks to see if the blank `option` exists for the `select` dropdown and sets the `allowClear` option accordingly.
> Allows select2 dropdowns to be cleared when the first option is blank

- app/assets/javascripts/activeadmin_addons/select2.js
- app/inputs/ajax_filter_input.rb
- docs/select2_search.md
- spec/dummy/app/admin/invoices.rb
@ldlsegovia I added preliminary support for filters, I haven't found a way to access url helpers on the filter DSL, so you can only use strings when defining the ajax `url: '/admin/users'`
This would  make issue #82 possible
> feat(AjaxFilterInput): Enable usage of ajax select2 in filters

- docs/paperclip_attachment.md
- lib/activeadmin_addons/addons/paperclip_attachment.rb
- spec/features/paperclip_attachment_spec.rb
Adds feature of giving a proc as label for attachment_column.  With this, for setting a label, you can access other attributes of the model, besides the file's filename.
> Proc as label for attachment_column

- Gemfile.lock
- activeadmin_addons.gemspec
- lib/activeadmin_addons/support/enumerize_formtastic_support.rb
It fixes deprecations described in https://github.com/platanus/activeadmin_addons/issues/85
and also fixes issue with enumerize 2.0+ described in https://github.com/platanus/activeadmin_addons/issues/77
> Use prepend instead of deprecated alias_method_chain.

- app/inputs/tags_input.rb
- docs/select2_tags.md
Why:
* When working with something like acts-as-taggable, we need the option to pass through values that aren't necessary id, but a custom formatted string from a method
This change addresses the need by:
* Adding the option values option to the tag component
* Updating the documentation
> Allow customizable select2 values for tag inputs

- app/inputs/date_time_picker_input.rb
- app/inputs/search_select_input.rb
When you use either :date_time_picker or :search_select in ActiveAdmin.register_page it was throwing errors because it was searching for the method in the model while there is no model. So, I put a condition, and it is working fine now in both ActiveAdmin Models and ActiveAdmin custom pages.
> Allow :date_time_picker and :search_select to be used in ActiveAdmin custom pages.

- app/assets/javascripts/activeadmin_addons/select2.js
- app/inputs/ajax_filter_input.rb
- app/inputs/search_select_input.rb
- docs/select2_search.md
- spec/features/select_2_spec.rb
Hi!
I've created this PR with this changes:
- add **order_by** param to Ajax Filter and Ajax Input to choose the attribute used to order the results. This is very useful if you choose a custom [rasacker](https://github.com/activerecord-hackery/ransack/wiki/using-ransackers) (eg `full_name`) as the search field (that field is not mapped as a real attribute in the DB so the default order gives an error during the query)
I hope this can help you and this PR can be merged.
Thanks
> Select2 custom ordering option

- app/inputs/tags_input.rb
Hi,
This change fixes incorrect HTML output when using tags component with model class inside a module like the bellow:
```html
<input id="service/category_industry_ids"
class="select2-tags"
data-model="service/category"
data-method="industry_ids"
data-collection="[...]"
type="text" value=""
name="service/category[industry_ids_str]" />
```
This should be
```html
<input id="service_category_industry_ids"
class="select2-tags"
data-model="service_category"
data-method="industry_ids"
data-collection="[...]"
type="text" value=""
name="service_category[industry_ids_str]" />
```
Model implementation is like this:
```rb
module Service
class Category
has_many :industries
end
end
```
> Replace slashes to underscore in module name

- app/inputs/ajax_filter_input.rb
When searching with the model association, use the `:class_name` if there is :class_name specified by the association.
For example:
```
class Category
belongs_to :organization, class_name: 'SomeOrg::Organization'
end
```
and visit `http://server/admin/categories?utf8=%E2%9C%93&q%5Borganization_id_eq%5D=ANWISB&commit=Filter&order=id_desc`
will cause error that says Can't find Category with id ANWISB
> Use the class_name specified by the association

- lib/activeadmin_addons/addons/state_values.rb
ActiveAdmin 1.1.0 deprecates `type` parameter: https://github.com/activeadmin/activeadmin/commit/484a0515b2f48a16dd511d60737801cdc4c65209
This change is compatible with previous versions, as `type` parameter will be `nil` (its default value) and the `class` option will have the CSS class that will be used.
> Removed deprecated `type` parameter

- CHANGELOG.md
- lib/activeadmin_addons/support/input_helpers/input_methods.rb
- spec/dummy/app/models/store/car.rb
- spec/dummy/app/models/store/manufacturer.rb
- spec/dummy/db/migrate/20170904155016_create_cars.rb
- spec/dummy/db/migrate/20170904155843_create_manufacturers.rb
- spec/dummy/db/schema.rb
- spec/lib/support/input_methods_spec.rb
Whenever the model had a namespace, the code was looking for the association class without namespace and that would raise an unwanted error. Example:
```ruby
module Store
class Car < ActiveRecord::Base
belongs_to :manufacturer # does not have a class_name option as both models are in the same namespace
end
class Manufacturer < ActiveRecord::Base
has_many :cars
end
end
ActiveAdmin.register Store::Car do
filter :manufacturer,
as: :search_select_filter,
url: proc { admin_store_manufacturers_path },
fields: [:name, :description],
display_name: "name"
end
```
The `filter` would raise:
```
uninitialized constant BarContentSection
activesupport (5.0.5) lib/active_support/inflector/methods.rb:268:in `const_get'
activesupport (5.0.5) lib/active_support/inflector/methods.rb:268:in `block in …
```
> Don't rely on :class_name option being set on association to identify its class

- lib/activeadmin_addons/active_admin_config.rb
add_classes_to_body is now deprecated.
This should not break on stable versions of AA
> alias build instead of add_classes_to_body

- lib/activeadmin_addons/support/input_helpers/select_helpers.rb
- spec/dummy/app/admin/invoices.rb
- spec/dummy/app/models/invoice.rb
- spec/features/inputs/tags_input_spec.rb
- spec/lib/support/select_helpers_spec.rb
```ruby
def method_model
object_class.reflect_on_association(association_name).try(:klass) ||
association_name.classify.constantize
end
```
I think `selected_collection#model_name` should be equal with `collection#model_name`
because `association_name` can be virtual attribute or other
ex:
```ruby
class Foo
has_many :other_bars, class_name: 'Bar'
attr_accessor :another_bar_ids
end
class Bar
end
```
I upgraded to the version 1.1.2 from version [0.10.1](https://github.com/platanus/activeadmin_addons/blob/v0.10.1/app/inputs/tags_input.rb#L13)
> feat(TagsInput): associated active record can use alias

- lib/activeadmin_addons/support/input_helpers/input_methods.rb
- lib/activeadmin_addons/support/input_helpers/select_helpers.rb
- Query once to get the collection on `SelectHelpers`
- Query once to get the selected item of the collection in `SelectHelpers`
- Query once to get the `input_value`
> fix(): Stop multiple requests in select

- docs/aasm_integration.md
- lib/activeadmin_addons/addons/state_builder.rb
- spec/dummy/app/models/invoice.rb
- spec/dummy/db/migrate/20180222225709_add_shipping_status_to_invoice.rb
- spec/dummy/db/schema.rb
- spec/features/state_builder_spec.rb
Rendering AASM state when having [multiple state machines per class](https://github.com/aasm/aasm/blob/master/README.md#multiple-state-machines-per-class) have problems, because at least one of them should be named, and now the StatesBuilder always use the default machine (named `:default`). This PR adds support for specifing the state machine name.
I added docs, but it seems that tests would requires much more work (I guess that I should have to add a new dummy model with two state machines), so I prefer to confirm that this feature is gonna be added before doing it. :grimacing:
> Named AASM machines support.

- activeadmin_addons.gemspec
This PR fixes an error in console which happens when you do `bundle update activeadmin_addons` with ruby 2.5.0:
```
/Users/lllukom/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/shell/basic.rb:90:in `=~': invalid byte sequence in US-ASCII (ArgumentError)
```
But the real error is:
```
[!] There was an error while loading `activeadmin_addons.gemspec`: invalid multibyte char (US-ASCII) - /Users/lllukom/.rvm/gems/ruby-2.5.0/bundler/gems/activeadmin_addons-f848255d1299/activeadmin_addons.gemspec:10: invalid multibyte char (US-ASCII). Bundler cannot continue.
>    s.authors     = ["Platanus", "Julio García", "Emilio Blanco", "Leandro Segovia"]
```
It appears that there is an invalid letter "i" with stress in author name `Julio García`. I've replaced it with an …
> fix invalid multibyte char (US-ASCII) error in activeadmin_addons.gemspec (ruby 2.5.0)

- Gemfile.lock
- activeadmin_addons.gemspec
- lib/activeadmin_addons/engine.rb
This removes the dependency on `sass-rails` and changes it to `sass`. To run tests, we add a development dependency on `sass-rails`. Then, to integrate with Rails apps, we try to first load `sassc-rails`, and if it doesn't exist, then we try to load `sass-rails`. If neither exists, we raise an exception.
This is all necessary to allow Rails apps to depend on the much faster [`sassc-rails`](https://github.com/sass/sassc-rails) gem.
Closes #225
> Use sass gem instead of sass-rails

- app/assets/javascripts/activeadmin_addons/addons/interactive_select_tag.js
- app/assets/javascripts/activeadmin_addons/addons/toggle_bool.js
- app/assets/javascripts/activeadmin_addons/config.js
- app/assets/javascripts/activeadmin_addons/inputs/color-picker.js
- app/assets/javascripts/activeadmin_addons/inputs/date-time-picker.js
- app/assets/javascripts/activeadmin_addons/inputs/nested-select.js
- app/assets/javascripts/activeadmin_addons/inputs/search-select.js
- app/assets/javascripts/activeadmin_addons/inputs/select2.js
- app/assets/javascripts/activeadmin_addons/inputs/selected-list.js
- app/assets/javascripts/activeadmin_addons/inputs/tags.js
In order to work properly on a rails app using turbolinks the javascript code
must be executed not only on document ready, as regular jQuery plugins do, but
also on "turbolinks:load" event.
This fixes issue #207
> Be nice with turbolinks

- app/assets/javascripts/activeadmin_addons/addons/toggle_bool.js
I'am using pundit on activeadmin, and because the CSRF is not set on the request, the request fail because is not authorized, I add this and it's works.
This happend when I add a custom table on the dashboard of activeadmin with `table_for` and added the column `toggle_bool_column`
> [add] csrf-token on headers request

- lib/activeadmin_addons/support/custom_builder.rb
Se agrega soporte a las clases decoradas. Esto se realizó obteniendo el nombre de la clase base en lugar de la clase en cuestión.
> fix(custom_builder): get class name from base class

- lib/activeadmin_addons/support/custom_builder.rb
When models registered in activeadmin are decorated or contain a module, the `class_name`  method in the `custom_builder.rb` was not working .
> fixed issue #224 - toggle_bool_column for modulized or decorated models

- .travis.yml
- Gemfile.lock
- activeadmin_addons.gemspec
- spec/rails_helper.rb
Recent PRs (such as #264 and #262) are currently blocked because of Travis errors that looks like this:
```
Selenium::WebDriver::Error::SessionNotCreatedError:
session not created: Chrome version must be between 70 and 73
(Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.4.0-101-generic x86_64)
```
This change replaces the deprecated chromedriver-helper gem with the webdrivers gem. As a result, we will automatically download the latest chromedriver and wire it up to Selenium before each test run.
(See deprecation note in readme of https://github.com/flavorjones/chromedriver-helper)
> Fix chrome tests

- app/assets/javascripts/activeadmin_addons/addons/interactive_select_tag.js
Related to #216, adds missing CSRF token on request for interactive select tag addon.
> Adds missing CSRF header for interactive select tag

- Gemfile.lock
- activeadmin_addons.gemspec
- lib/activeadmin_addons/engine.rb
Per https://sass-lang.com/ruby-sass the `sass` library reached end of life 2019-03-26. This replaces that library with `sassc`.
This resolves https://github.com/platanus/activeadmin_addons/issues/266
> Replace EOL'd sass with sassc

- .gitignore
- Gemfile.lock
- activeadmin_addons.gemspec
- app/assets/javascripts/activeadmin_addons/all.js
- lib/activeadmin_addons/engine.rb
- spec/dummy/db/schema.rb
- vendor/assets/select2/select2.css
- vendor/assets/select2/select2.full.js
* select2-rails is no longer supported, so we will vendor the files directly
* Bring in latest version of select2 (4.0.7). These files were pulled from the dist folder of https://github.com/select2/select2/archive/4.0.7.zip
* Add vendor/bundle to .gitignore for convenience locally
* Update db/schema for test db due to recent formatting changes in ActiveRecord (no substantive changes)
Fixes #263
> Remove select2-rails and upgrade to select2 4.0.7

- .rubocop.yml
- app/assets/javascripts/activeadmin_addons/inputs/nested-select.js
- spec/dummy/app/admin/departments.rb
- spec/dummy/app/models/department.rb
- spec/dummy/app/models/departments_city.rb
- spec/dummy/db/migrate/20180228085959_create_departments.rb
- spec/dummy/db/migrate/20180228122115_create_departments_cities.rb
- spec/dummy/db/schema.rb
- spec/features/inputs/nested_select_input_spec.rb
- spec/support/capybara_helpers.rb
Fixed style issues of #164. Eslint is happy now
There are currently no nested forms in the test setup that can be used to test this.
I could add a new "citygroup" that contains multiple cities and uses a nested form
> fix nested select when used inside a nested form

- .rubocop.yml
only ignore autogenerated file
> chore(rubocop): change exclusion rule to include migrations

- lib/activeadmin_addons/active_admin_config.rb
- lib/activeadmin_addons/support/input_base.rb
- spec/features/inputs/select2_spec.rb
Debugging some HTML issues with the w3c validator I ran into some errors that were caused by this gem.
- A second `body` element is created at the end of the page to add the `data-default-select` attribute. As the HTML spec only allows for a single `body` element, this fixes that by adding the attribute to the existing body element.
- All addon inputs inherit from formtastic's `StringInput` which adds the attributes `maxlength` and `size` to every input. This is also invalid HTML because these attributes are only valid for `input` with certain types such as text.
> Fix invalid html generation

- lib/activeadmin_addons/addons/toggle_bool_builder.rb
- lib/activeadmin_addons/support/custom_builder.rb
- spec/features/toggle_bool_builder_spec.rb
toggle bool selector must disappear if update option is disabled.
```ruby
ActiveAdmin.register Invoice do
actions :index
index do
toggle_bool_column :active
end
end
```
toggle bool selector must disappear if update option is disabled.
```ruby
ActiveAdmin.register Invoice do
actions :index, :update
index do
toggle_bool_column :active
end
end
```
> fix(toggle-bool-builder): show if update action is enabled only

- app/inputs/active_admin/inputs/select_input.rb
- docs/select2_default.md
- spec/features/inputs/select2_spec.rb
This PR adds the `tags` option to the default form select input. It adds [dynamic option creation](https://select2.org/tagging) to select2. Things to consider:
- Select 2 supports [options via data-* attributes](https://select2.org/configuration/data-attributes), so it wasn't needed to change the js that initializes the select2
- At first I tried defining a `SelectInput` (without the `ActiveAdmin::Inputs::`) but it would override [activeadmin's select input definition for filters](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/filters/select_input.rb), and those would fail. To sidestep this I defined it as `ActiveAdmin::Inputs::SelectInput`, which allowed these changes to only apply to regular form inputs because of [the order in which filters lookup input …
> Default select tags support

- lib/activeadmin_addons/support/input_helpers/input_methods.rb
- spec/lib/support/input_methods_spec.rb
When the filter joins relations or attempts to match attributes in the other table (valid Ransack query), the `search_select_filter` is not able to detect the "method_model" (model class being filtered).
Example:
```ruby
class Post < ApplicationRecord
belongs_to :author_profile, class_name: "Profile"
end
class Profile < ApplicationRecord
has_many :posts
belongs_to :user
end
class User < ApplicationRecord
has_one :profile
end
```
```ruby
ActiveAdmin.register Post do
filter :author_profile_user_id, as: :search_select_filter, url: proc { admin_users_path }
end
```
That raises an error "undefined constant AuthorProfileUser".
With this change, the "method_model" can be provided via options:
```ruby
ActiveAdmin.register Post do
filter :author_profile_user_id, as: :search_select_filter, url: …
```
> Allow 'method_model' to be provided as an option to `filter`

- Rakefile
- app/assets/javascripts/activeadmin_addons/all.js
- app/assets/stylesheets/activeadmin_addons/imports/jquery-datepicker.scss
- app/assets/stylesheets/activeadmin_addons/imports/webpack/jquery-datepicker.scss
- package.json
- spec/dummy/app/javascript/stylesheets/active_admin.scss
- spec/dummy/package.json
- spec/dummy/yarn.lock
- yarn.lock
- Uses js and scss from source instead of node_modules with webpacker mode.
- Adds jquery.xdan.datetimepicker's css code into addons to avoid webpack/sprockets incompatibility.
> refactor(): use scss files from source instead of node modules

- CHANGELOG.md
- docs/enum_integration.md
- lib/activeadmin_addons/addons/tag_builder.rb
```ruby
ActiveAdmin.register Invoice do
show do
attributes_table do
end
panel 'Documents' do
table_for user.documents do
tag_column(:state, intercative: true)
end
end
end
end
```
Previous code was generating invalid `/admin/invoices/:id` instead of `/admin/documents/:id` working with interactive tag column.
> fix(tag-builder): generating wrong path with nested resources

- lib/activeadmin_addons/support/enum_utils.rb
- spec/features/tag_builder_spec.rb
- spec/lib/support/enum_utils_spec.rb
In #442 we added support for automatic enum translation for Rails built-in enums
This PR fixes an issue that would show the whole enum hash as the translation for an empty value when using `tag_column` or `tag_row`. Thanks to @stadia for [reporting this issue](https://github.com/platanus/activeadmin_addons/commit/beb1cd846f70598189183506384c7b8f44b64d8d#r103193306).
The fix returns nil as the translation for a blank value. Returning nil instead of an empty string keeps the same behavior as before the translation changes, which uses [activeadmin's default translation for unset value](https://github.com/activeadmin/activeadmin/blob/51689e48ec3faa51127b8462b2219e5e0c09ad8a/config/locales/en.yml#L66)
**Before translation changes**
**After translation changes, before fix**
**After fix**
I'm …
> fix(enum-utils): return nil if option name is blank

- app/javascript/activeadmin_addons/stylesheets/all.scss
There seems to be a problem finding the datepicker SCSS as the file is not exposed in the package's package.json.
It's probably solvable in some other way but we're already including the file anyway so there's no need to import it directly from node_modules.
> fix(scss): fix datepicker import

- app/javascript/activeadmin_addons/inputs/slim-select.js
- Fixes the width of the slim-select inputs inside the filters by copying the style that would have been applied to the original selects (unless the select is empty)
- Copies the font-size from the select
Since we're using the styles applied by the theme, the fix should be compatible with other themes besides the default one.
Before:
After:
Default theme:
Arctic Admin:
> Fix filters style

- .circleci/config.yml
- .rubocop.yml
- CHANGELOG.md
- activeadmin_addons.gemspec
This Pull Request has been created because we are supporting ruby 2.6, which has been in EOL for a year. Having 2.6 in our test suite throws error when upgrading nokogiri dependency:
This Pull Request changes removes 2.6 from CI, and sets `required_ruby_version` in gemspec
> Define required ruby version to >=2.7.0

- CHANGELOG.md
- app/inputs/tags_input.rb
- app/javascript/activeadmin_addons/inputs/slim-select-tags.js
- docs/slim-select_tags.md
- spec/features/inputs/tags_input_spec.rb
This Pull Request has been created because tags input has had some inconsistent behaviors in the past related to the string returned and the token that separated the tags in said string. Plus, it seemed a bit counter-intuitive that a tags/multiselect input returned a string instead of an array.
Closes #335 
Closes #341 
Closes #421 
This Pull Request changes the tags input so it returns an array of strings instead of a token-separated string. It does so by relying on the default behavior of a regular rails select with `multiple: true`. This allowed me to simplify the input a lot, as now a couple of things, such as hidden input with blank value and tracking of the array value, are done under the hood.
The input now works almost identically as doing `f.input :foos, as: :select, multiple: …
> feat(tags-input): rework to return array

- .circleci/config.yml
- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/activeadmin_addons/version.rb
- package.json
This Pull Request has been created because:
- We have some unreleased changes
- We have automated the publishing in rubygems but not npm
This Pull Request:
- Configures CI to publish to NPM whenever a new tag is pushed. Done following [this guide](https://circleci.com/docs/deploy-to-npm-registry/)
- Bumps gem and npm package version. From this version on, we are going to keep the same version for both. Thanks to @filipkis for [their suggestion](https://github.com/platanus/activeadmin_addons/issues/358)
- Updates Changelog. Added a beta.1 entry to indicate it was skipped to have both libraries in the same version
- Updates README's Publishing section
> Release beta 2 and configure npm auto deploy

- .circleci/config.yml
- Gemfile.lock
- activeadmin_addons.gemspec
- spec/rails_helper.rb
This Pull Request has been created because chromedriver recently made some changes to the location of their new versions, and that caused errors when running tests that used capybara/selenium.
This Pull Request changes some gems to fix the issue, following [this conversation in a webdrivers issue](https://github.com/titusfortner/webdrivers/issues/247).
- Replaces `capybara-selenium` with `capybara`
- Updates `capybara` version
- Replaces `webdrivers` with `selenium-webdriver`
- Removes some unused and now deprecated config in `rails_helper`
> fix(tests): fix chromedriver error for capybara tests

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- app/inputs/nested_level_input.rb
- app/inputs/search_select_input.rb
- app/inputs/selected_list_input.rb
- docs/slim-select_nested_select.md
- docs/slim-select_search.md
- docs/slim-select_selected_list.md
- spec/dummy/app/models/category.rb
- spec/dummy/app/models/city.rb
- spec/dummy/app/models/country.rb
- spec/dummy/app/models/invoice.rb
- spec/dummy/app/models/item.rb
- spec/dummy/app/models/region.rb
- spec/dummy/config/initializers/active_admin.rb
- spec/features/inputs/nested_select_input_spec.rb
This Pull Request has been created because ActiveAdmin [released v3](https://github.com/activeadmin/activeadmin/releases/tag/v3.0.0) 🎉 . It has some breaking changes, including [requiring of ransack v4](https://github.com/activerecord-hackery/ransack/releases/tag/v4.0.0), so some changes needed to be done on our part to support it.
This Pull Request applies a couple of backwards compatible changes that allow this gem to work well with AA v3, and for tests to pass using that version:
- Adds `ransackable_attributes` and `ransackable_associations` to dummy app models, as it is now [explicitly required by ransack v4](https://github.com/activerecord-hackery/ransack/pull/1400)
- Removes some filter predicates (pretty much just `contains`), that [are now removed from …
> Activeadmin v3 support

- Gemfile.lock
- activeadmin_addons.gemspec
v1 version of `activeadmin_addons` has a dependency on `active_material` gem. `active_material` gem had recently a new [release](https://rubygems.org/gems/active_material/versions/2.1.1) that relies on ruby 3.1 built-in methods without setting it in `required_ruby_version`.  That leads the app running on ruby 3.0 to crash. 
It can be fixed if a dependency on `active_material` had more specific range like `(~> 1.5)` or `(~> 1.5.2)`
I've also sent a PR to active_material https://github.com/dkniffin/active_material/pull/100
* [N/A] Tests are added or updated if you fix a bug or add a feature.
* [N/A] Documentation has been added or updated if you add a feature or modify an existing one.
* [N/A] CHANGELOG files are updated for the …
> Pin active_material to earlier version

- app/javascript/activeadmin_addons/stylesheets/inputs/date-time-picker-filter.scss
Addressed sass deprecation warning.
The following deprecation warning was addressed.
```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
More info: https://sass-lang.com/d/mixed-decls
╷
5   │ ┌     label {
6   │ │       display: none;
7   │ │     }
│ └─── nested rule
... │
5   │ ┌     label {
6   │ │       display: none;
7   │ │     }
│ └─── nested rule
... │
9   │       margin-bottom: 5px;
│       ^^^^^^^^^^^^^^^^^^ declaration
╵
vendor/bundle/gems/activeadmin_addons-1.10.1/app/assets/stylesheets/activeadmin_addons/inputs/date-ti …
```
> Suppress sass deprecation warning

- app/assets/javascripts/activeadmin_addons/all.js
- app/javascript/activeadmin_addons/inputs/selected-list.js
- When searching for multiple fields including `id`, other searchable inputs force the `predicate` to `eq` rather than `cont`, and `selected-list` does not, which results in a SQL error. 
This Pull Request changes the `predicate` to `eq` when the field is `id`.
From:
```
{"groupings"=>{"0"=>{"m"=>"or", "name_cont"=>"test", "id_cont"=>"test"}}, "combinator"=>"and"}
```
To:
```
{"groupings"=>{"0"=>{"m"=>"or", "name_cont"=>"test", "id_eq"=>"test"}}, "combinator"=>"and"}
```
> Fix searching for ids with selected list input

- CHANGELOG.md
- app/javascript/activeadmin_addons/addons/toggle_bool.js
- docs/toggle_bool.md
- lib/activeadmin_addons/addons/toggle_bool_builder.rb
Add new confirm_message feature to toggle-bool-switch: https://github.com/platanus/activeadmin_addons/issues/483
> Add confirm_message to toggle-bool-switch

- CHANGELOG.md
- app/inputs/selected_list_input.rb
Closes #502
actionview >7.2 [raises an error](https://github.com/rails/rails/blob/91d456366638ac6c3f6dec38670c8ada5e7c69b1/actionview/lib/action_view/helpers/tag_helper.rb#L516-L517) in `content_tag` if the tag name isn't valid in HTML5.
Removes the invalid HTML from `render_control_wrapper`. The `label_html` is already rendered in `render_custom_html`, matching the other input implementations.
* _I think this would be covered by testing the whole gem against Rails 7.2 in a separate PR._
> Fix invalid HTML in selected list causing error in Rails 7.2

- CHANGELOG.md
- app/inputs/selected_list_input.rb
The same as #506 but for v1, thanks @quadule for the PR and @tobischo for reporting the issue. 
Basically removes a redundant line intended for creating the label for the input.
The line had 2 issues:
1. The label was already created in a "parent" method ([here](https://github.com/platanus/activeadmin_addons/blob/v1/app/inputs/selected_list_input.rb#L3)).
2. The `content_tag` method was called incorrectly, with the whole label as argument instead of the tag type as first argument and options as second. It was generating invalid HTML, eg. `<_label_for__X__class__label__Y__label_></_label_for__X__class__label__Y__label_>` which was completely malformed.
> fix(selected-list): remove redundant (and w/ invalid html) label
