README.md, docs/enumerize_integration.md, lib/activeadmin_addons/addons/enum_tag.rb, lib/activeadmin_addons/engine.rb
Adds active admin tags matching enumerize attributes
=> feat(): add enumerize support

lib/activeadmin_addons/addons/bool_values.rb
- Support methods as attributes
- Support blocks and custom labels
=> Improve bool

app/assets/javascripts/activeadmin_addons/select2.js
Check it out @ldlsegovia
[Closes #23]
PS: Thanks @juliogarciag for the tip
=> fix(Select2): Fix select2 not applied to has_many

lib/activeadmin_addons/addons/enum_tag.rb
This adds support for builtin enums
[Closes #26]
=> feat(Enum): Support Rails 4.1+ enums

app/assets/javascripts/activeadmin_addons/select2.js, app/inputs/search_select_input.rb, docs/select2_search.md
The hardcoded value of 1 may not be suitable beyond a certain number of records.
=> Allow overriding select2 minimum input length

app/inputs/search_select_input.rb, docs/select2_search.md, spec/features/select_2_spec.rb
I added a new options for search_select
=> Adding class option for search_select

app/inputs/nested_select_input.rb, spec/features/select_2_spec.rb
The nested input was ignoring custom urls
=> fix(Select2.Nested): Fix input ignoring custom URL

README.md, docs/select2_default.md, docs/select2_nested_select.md, docs/select2_search.md
@ldlsegovia I did some minor fixes to the documentation. I hope you like them.
=> docs():several opinionated fixes

README.md, docs/install_generator.md, lib/generators/activeadmin_addons/install/install_generator.rb
This PR adds a Rails Generator that automatically modifies ActiveAdmin JS and CSS files to successfully add ActiveadminAddons.
=> feat(generator):add automatic setup to fullfil #45

lib/activeadmin_addons/addons/list.rb
=> feat(List): Allow nil values in column_list and row_list

app/assets/javascripts/activeadmin_addons/select2.js
Reinitialization of already inited Select2 objects was happend after clicking on has_many_add
=> fix reinitialization on add new has_many fieldset

docs/boolean_values.md, lib/activeadmin_addons/addons/bool_values.rb, spec/dummy/app/assets/stylesheets/active_admin.scss, spec/features/bool_values_spec.rb
=> feat(): add custom css class for bool_row and bool_column

app/inputs/ajax_filter_input.rb
Adds ability to create a dynamic urls using a proc scoped to the template
```
filter :user_id, as: :ajax_filter, url: proc { admin_community_users_path(community_id: params[:community_id]) }, fields: [:username], display_name: 'username'
=> Add support for proc url

app/assets/javascripts/activeadmin_addons/select2.js
https://github.com/activerecord-hackery/ransack/issues/85
=> Use _eq if field name is id, as ransack doesn't support id_cont

app/inputs/date_time_picker_input.rb
Thanks for this gem! 
Let me know if I need to add spec etc. 
This is stolen from:
https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/inputs/date_picker_input.rb#L84
=> Respect date_time_picker input_html[:value]

app/assets/javascripts/activeadmin_addons/select2.js
https://github.com/platanus/activeadmin_addons/issues/95
=> Enable allowClear in select2_search (AJAX one)

lib/activeadmin_addons/support/custom_builder.rb
Demodulize and underscore the record's class name in custom builder
=> Fix Custom Builder Class Name

.travis.yml, Gemfile.lock, activeadmin_addons.gemspec, spec/features/inputs/nested_select_input_spec.rb, spec/features/toggle_bool_builder_spec.rb, spec/rails_helper.rb
Replace firefox config with chromedriver --headless as requested in [#175](https://github.com/platanus/activeadmin_addons/issues/175).
=> Chromedriver with Capybara

lib/activeadmin_addons/addons/toggle_bool_builder.rb
=> fix(): change syntax to play nice with ruby v2.1.2

docs/select2_nested_select.md
I wasted a bit of time to figure out functionality, so this might be useful to mention in the docs.
=> docs(): mention minimum_input_length=0 for nested select

CHANGELOG.md, Gemfile.lock, activeadmin_addons.gemspec
=> fix(): use pessimistic version for require_all gem

lib/activeadmin_addons/addons/toggle_bool_builder.rb, spec/dummy/app/models/category.rb, spec/features/toggle_bool_builder_spec.rb
hey @ldlsegovia ! 
A little PR to support toggle bool in `table_for`
=> fix(ToggleBool): Allow toggle bool in table_for

CHANGELOG.md, Gemfile.lock, activeadmin_addons.gemspec
to avoid unable to connect to chromedriver http://127.0.0.1:9515
=> fix(): add chromedriver-helper gem

CHANGELOG.md, app/inputs/nested_select_input.rb
=> feat(nested-select): allow to work with non virtual attributes too

CHANGELOG.md, lib/activeadmin_addons/addons/attachment_builder.rb, lib/activeadmin_addons/addons/image_builder.rb
=> feat(): image and attachment builders don't ask file existence anymore

vendor/assets/select2/select2.css, vendor/assets/select2/select2.full.js
Updates select2 to version 4.0.13 using the files from https://github.com/select2/select2/archive/4.0.13.zip
=> chore(select2): bump version to 4.0.13

Gemfile.lock, activeadmin_addons.gemspec, lib/activeadmin_addons/support/input_base.rb, lib/activeadmin_addons/support/input_helpers/filter_input.rb, lib/activeadmin_addons/support/input_helpers/filter_input_methods.rb
Update `require_all` gem
Update Gemfile
Add `require` to the files that needed
Fix #311
=> chore(require_all): update gem to 2.0

app/inputs/date_range_input.rb, app/inputs/date_time_picker_input.rb
=> Set autocomplete to off as default option on date inputs

CHANGELOG.md
I went through all the PRs merged after 1.7.1 Think I got everything but I might have missed something.
Also added links to PRs for reference
=> docs(changelog): add unreleased changes entry

Gemfile.lock, activeadmin_addons.gemspec
Bumped `require_all` gem version to the latest one, that being `3.0`.
Ran the specs and tested the project and everything seems to be working as expected.
=> Bump require_all gem version to 3.0

docs/install_generator.md
I noticed when I tried this that the import, it wasnt working properly, swapping to the above import worked (had to inspect the node_modules folder.)
=> Fix import of SCSS in webpacker.

CHANGELOG.md, activeadmin_addons.gemspec
Removes vendor directory from build to reduce gem size
=> fix(): ignore vendor directory

CHANGELOG.md, app/inputs/active_admin/inputs/select_input.rb, spec/features/inputs/select2_spec.rb
It fix this issue https://github.com/platanus/activeadmin_addons/issues/363
=> fix(select): tags option not working with active_admin_form_for

CHANGELOG.md, app/inputs/date_range_input.rb, lib/generators/activeadmin_addons/install/install_generator.rb
=> Fix `DateRangeInput#input_html_options` override

lib/activeadmin_addons/support/set_datepicker.rb, spec/dummy/app/admin/invoices.rb, spec/dummy/app/admin/items.rb, spec/dummy/app/views/admin/invoices/_formtastic_form.html.erb, spec/dummy/db/migrate/20140530172044_create_invoices.rb, spec/dummy/db/schema.rb, spec/dummy/lib/fake_data_loader.rb
=> fix default date picker

CHANGELOG.md, app/inputs/date_time_picker_input.rb, spec/features/inputs/date_time_picker_spec.rb
=> Datepicker options not overriding default options properly

CHANGELOG.md, app/inputs/nested_select_input.rb, lib/activeadmin_addons/support/input_helpers/input_html_helpers.rb, lib/activeadmin_addons/support/input_helpers/input_methods.rb, lib/activeadmin_addons/support/input_helpers/input_options_handler.rb, lib/activeadmin_addons/support/input_helpers/select_helpers.rb, spec/features/inputs/tags_input_spec.rb, spec/lib/support/input_methods_spec.rb, spec/lib/support/select_helpers_spec.rb
=> Fix select2 association

app/assets/javascripts/activeadmin_addons/all.js, app/javascript/activeadmin_addons/addons/interactive_select_tag.js, app/javascript/activeadmin_addons/addons/toggle_bool.js, app/javascript/activeadmin_addons/config.js, app/javascript/activeadmin_addons/inputs/color-picker.js, app/javascript/activeadmin_addons/inputs/date-time-picker.js, app/javascript/activeadmin_addons/inputs/nested-select.js, app/javascript/activeadmin_addons/inputs/search-select.js, app/javascript/activeadmin_addons/inputs/select2.js, app/javascript/activeadmin_addons/inputs/selected-list.js, app/javascript/activeadmin_addons/inputs/tags.js
This will make activeadmin_addons play nice with turbo, as well as turbolinks
=> Add turbo event

spec/rails_helper.rb
Requires rspec-retry and adds more verbose error messages
=> fix(rspec): fix rspec-retry

CHANGELOG.md, Gemfile.lock, lib/activeadmin_addons/version.rb, lib/generators/activeadmin_addons/webpacker/webpacker_generator.rb, package.json, yarn.lock
=> V2.0.0.beta.0

docs/date-time-picker.md, lib/generators/activeadmin_addons/install/templates/initializer.rb, spec/dummy/config/initializers/activeadmin_addons.rb
Just some typos about the word "You" that I notice. This PR fixes them. Thanks for your work!
=> Fix - typo fix about the word 'You'

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, README.md, docs/CONTRIBUTING.md
This Pull Request has been created because we don't have much structure for people to contribute to this gem, which could cause confussion or result in missing information.
This Pull Request adds some contributing guidelines and rules:
- Adds issue templates for bug reports and feature requests
- Adds PR template
- Changes some outdated things in contributing.md and readme, as well as changes some wordings
- PR template based on [rails own template](https://github.com/rails/rails/blob/main/.github/pull_request_template.md)
- Issues based on default templates for bugs and features that github provides
=> Contributing changes

.pryrc, .rubocop.yml, Gemfile.lock, activeadmin_addons.gemspec
This Pull Request has been created to make debugging in development env easier, and closer to what we use in other projects.
The following changes were made:
- Adds pry-byebug
- Adds pry-byebug shortcuts
- Disables autocorrect for Rspec/Focus rule, to be able to use `fit`, `fcontext` and `fdescribe` when debugging without the "f" disappearing when saving
[pry-byebug](https://github.com/deivid-rodriguez/pry-byebug)
=> Dev debugging improvements

CHANGELOG.md
I was just browsing your changelog when I spotted this bad link.
=> Fix link to PR #451 in CHANGELOG.md

CHANGELOG.md, Gemfile.lock, lib/activeadmin_addons/version.rb, package.json
This Pull Request has been created to prepare for release of v2 beta.3
This Pull Request bumps version of gem and package, as well as updates the changelog, including release of 1.10.1 via #479. I'm not sure if the order I put it in the changelog is OK.
=> feat(): release v2 beta.3

docs/slim-select_default.md
This Pull Request has been created because there's a typo in README sample codes.
This Pull Request changes a typo in README sample codes.
=> Fix typo in slim-select_default.md

CHANGELOG.md, lib/activeadmin_addons/version.rb
=> feat: release v1.10.2

CHANGELOG.md, Gemfile.lock, lib/activeadmin_addons/version.rb, package.json
Releasing v2 beta 4. 
Small release of minor changes and fixes, it's been a while.
This release should improve compatibility with newer versions of rails, like 7.2.
=> feat: release v2.0.0.beta.4
